name: Sensible Web Development
markdown: redcarpet
redcarpet:
  extensions:
    - tables
    - with_toc_data
    - fenced_code_blocks
highlighter: pygments
baseurl: ''
tracking_id: UA-40241848-2
tracking_property: qrohlf.com
github_repo: qrohlf/sensible-web-development
exclude: [compass.rb, config.ru, Gemfile, Gemfile.lock, Procfile, Rakefile, README.md, sass, unicorn.rb, vendor]
collections:
  chapters:
    output: true
